# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
   configuration: checkbox-ng/docs/conf.py

# Python requirements to build the docs
# See: <https://docs.readthedocs.io/en/stable/faq.html#can-i-document-a-python-
# package-that-is-not-at-the-root-of-my-repository>
python:
   install:
   - requirements: checkbox-ng/docs/requirements.txt
