name: Rebuild checkbox.readthedocs.io
on:
  pull_request:
    types:
      - closed
    paths:
      - 'checkbox-ng/docs/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -X POST -d "branches=latest" -d "token=${{ secrets.RTD_TOKEN }}" https://readthedocs.org/api/v2/webhook/checkbox/137367/
